import { Book } from "./book";

export const READING_LIST: Book[] = [
  // --- greek ---
  // LITERATURE AND MYTHOLOGY
  {
    title: "The Iliad",
    author: "Homer",
    translation: "(translated by Emily Wilson)",
    year: -750,
    genre: "literature",
    category: "greek",
    notesPath: "/notes/iliad.md",
    done: true,
    cover: "/covers/iliad.jpeg",
    link: "https://www.amazon.com/Iliad-Homer/dp/1324001801",
    spine: "/spines/iliad-spine.png",
    rating: 5,
  },
  {
    title: "The Odyssey",
    author: "Homer",
    translation: "(translated by Emily Wilson)",
    year: -725,
    genre: "literature",
    category: "greek",
    notesPath: "/notes/odyssey.md",
    done: true,
    cover: "/covers/odyssey.jpeg",
    link: "https://www.amazon.com/Odyssey-Homer/dp/0393089053",
    spine: "/spines/odyssey-spine.jpeg",
    rating: 4,
  },
  {
    title: "An Oresteia",
    author: "Aeschylus, Sophocles, Euripides",
    translation: "(translated by Anne Carson)",
    year: -458,
    genre: "literature",
    category: "greek",
    notesPath: "/notes/oresteia.md",
    done: true,
    cover: "/covers/oresteia.jpg",
    link: "https://www.amazon.com/Oresteia-Agamemnon-Aiskhylos-Sophokles-Euripides/dp/086547916X",
    spine: "/spines/oresteia-spine.jpg",
    rating: 4.5,
  },
  {
    title: "Theogony & Works and Days",
    author: "Hesiod",
    translation: "(translated by M.L. West)",
    year: -700,
    genre: "literature",
    category: "greek",
    notesPath: "/notes/hesiod.md",
    done: true,
    cover: "/covers/hesiod.jpeg",
    link: "https://www.amazon.com/Theogony-Works-Oxford-Worlds-Classics/dp/019953831X/",
    spine: "/spines/theogony-spine.jpg",
    rating: 1,
  },
  // HISTORY
  {
    title: "The Histories",
    author: "Herodotus",
    translation: "(translated by Aubrey de Sélincourt)",
    year: -440,
    genre: "history",
    category: "greek",
    notesPath: "/notes/herodotus.md",
    done: true,
    cover: "/covers/herodotus.jpg",
    link: "https://www.amazon.com/Histories-Herodotus-dp-0140449086/dp/0140449086/",
    spine: "/spines/herodotus-spine.jpg",
    rating: 3.5,
  },
  {
    title: "History of the Peloponnesian War",
    author: "Thucydides",
    translation: "(translated by Rex Warner)",
    year: -400,
    genre: "history",
    category: "greek",
    notesPath: "/notes/thucydides.md",
    done: true,
    cover: "/covers/thucydides.jpg",
    link: "https://www.amazon.com/History-Peloponnesian-War-Thucydides/dp/0140440399",
    spine: "/spines/thucydides-spine.jpeg",
    rating: 5,
  },
  {
    title: "A History of My Times",
    author: "Xenophon",
    translation: "(translated by Rex Warner)",
    year: -360,
    genre: "history",
    category: "greek",
    notesPath: "/notes/xenophon.md",
    done: true,
    cover: "/covers/xenophon.jpg",
    link: "https://www.amazon.com/History-My-Times-Penguin-Classics/dp/0140441751",
    spine: "/spines/xenophon-spine.jpg",
    rating: 4.5,
  },
  // PHILOSOPHY
  {
    title: "The Last Days of Socrates",
    author: "Plato",
    year: -399,
    genre: "philosophy",
    category: "greek",
    done: true,
    notesPath: "/notes/socrates.md",
    cover: "/covers/socrates.jpg",
    link: "https://www.amazon.com/Last-Days-Socrates-Penguin-Classics-ebook/dp/B002RI9XUG",
    spine: "/spines/socrates-spine.jpg",
    rating: 5,
  },
  {
    title: "The Symposium",
    author: "Plato",
    year: -385,
    genre: "philosophy",
    category: "greek",
    done: true,
    notesPath: "/notes/symposium.md",
    cover: "/covers/symposium.jpg",
    link: "https://www.amazon.com/Symposium-Oxford-Worlds-Classics-Plato/dp/0199540195",
    spine: "/spines/symposium-spine.jpg",
    rating: 4.5,
  },
  {
    title: "The Republic",
    author: "Plato",
    year: -375,
    genre: "philosophy",
    category: "greek",
    done: true,
    notesPath: "/notes/republic.md",
    cover: "/covers/republic.jpg",
    link: "https://www.amazon.com/Republic-Plato/dp/0141442433/",
    spine: "/spines/republic-spine.jpg",
    rating: 5,
  },
  {
    title: "Nichomachean Ethics",
    author: "Aristotle",
    year: -340,
    genre: "philosophy",
    category: "greek",
    done: true,
    notesPath: "/notes/ethics.md",
    cover: "/covers/ethics.jpg",
    link: "https://www.amazon.com/Nicomachean-Ethics-Penguin-Classics/dp/0140455477",
    spine: "/spines/ethics-spine.jpg",
    rating: 4.5,
  },
  {
    title: "Politics",
    author: "Aristotle",
    year: -330,
    genre: "philosophy",
    category: "greek",
    done: true,
    notesPath: "/notes/politics.md",
    cover: "/covers/politics.jpg",
    link: "https://www.amazon.com/Politics-Penguin-Classics-Aristotle/dp/0140444211/",
    spine: "/spines/politics-spine.jpg",
    rating: 4.5,
  },
  // HELLENISTIC BRIDGE
  // {
  //   id: "diodorus-history",
  //   title: "Bibliotheca Historica",
  //   author: "Diodorus Siculus",
  //   year: -30,
  //   genre: "history",
  //   category: "greek",
  //   cover: "/covers/diodorus.jpg",
  //   done: false,
  // },
  // {
  //   id: "polybius-histories",
  //   title: "Histories",
  //   author: "Polybius",
  //   year: -118,
  //   genre: "history",
  //   category: "greek",
  //   done: false,
  // },
  // {
  //   id: "caesar-gallic",
  //   title: "The Gallic Wars",
  //   author: "Julius Caesar",
  //   year: -50,
  //   genre: "history",
  //   category: "roman",
  //   done: false,
  // },
  // {
  //   id: "caesar-civil",
  //   title: "The Civil War",
  //   author: "Julius Caesar",
  //   year: -45,
  //   genre: "history",
  //   category: "roman",
  //   done: false,
  // },
  // ROMAN IMPERIAL LITERATURE
  {
    title: "The Aeneid",
    author: "Virgil",
    year: -19,
    genre: "literature",
    category: "roman",
    done: true,
    notesPath: "/notes/aeneid.md",
    cover: "/covers/aeneid.jpg",
    link: "https://www.amazon.com/Aeneid-Virgil/dp/1324096438/",
    spine: "/spines/aeneid-spine.jpg",
    rating: 4.5,
  },
  {
    title: "The Odes",
    author: "Horace",
    year: -13,
    genre: "literature",
    category: "roman",
    done: true,
    notesPath: "/notes/odes.md",
    cover: "/covers/odes.jpg",
    link: "https://www.amazon.com/Odes-Horace/dp/0374525722/",
    spine: "/spines/odes-spine.png",
    rating: 4.5,
  },
  {
    title: "Metamorphoses",
    author: "Ovid",
    year: 8,
    genre: "literature",
    category: "roman",
    cover: "/covers/ovid.jpg",
    link: "https://www.amazon.com/Metamorphoses-New-Translation-Ovid/dp/039332642X/",
  },
  {
    title: "The Early History of Rome",
    author: "Livy",
    year: 9,
    genre: "literature",
    category: "roman",
  },
  // {
  //   id: "sallust-catiline",
  //   title: "Catiline's War, The Jugurthine War, Histories",
  //   author: "Sallust",
  //   year: -35,
  //   genre: "history",
  //   category: "roman",
  //   done: false,
  // },
  {
    title: "Plutarch's Lives Volume 1",
    author: "Plutarch",
    year: 100,
    genre: "history",
    category: "roman",
  },
  {
    title: "Plutarch's Lives Volume 2",
    author: "Plutarch",
    year: 100,
    genre: "history",
    category: "roman",
  },
  // {
  //   id: "appian-wars",
  //   title: "Civil Wars",
  //   author: "Appian",
  //   year: 150,
  //   genre: "history",
  //   category: "roman",

  //   done: false,
  // },
  // RISE OF THE EMPIRE
  // {
  //   id: "augustus-res-gestae",
  //   title: "Res Gestae Divi Augusti",
  //   author: "Augustus",
  //   year: 14,
  //   genre: "history",
  //   category: "roman",

  //   done: false,
  // },
  // {
  //   id: "lucan-pharsalia",
  //   title: "Pharsalia",
  //   author: "Lucan",
  //   year: 61,
  //   genre: "literature",
  //   category: "roman",
  //   done: false,
  // },

  // ROMAN IMPERIAL HISTORY
  {
    title: "The Annals and The Histories",
    author: "Tacitus",
    year: 110,
    genre: "history",
    category: "roman",
  },
  // {
  //   id: "tacitus-histories",
  //   title: "The Histories",
  //   author: "Tacitus",
  //   year: 105,
  //   genre: "history",
  //   category: "roman",

  //   done: false,
  // },
  {
    title: "The Jewish War",
    author: "Josephus",
    year: 75,
    genre: "history",
    category: "roman",
  },
  {
    title: "On the Nature of Things",
    author: "Lucretius",
    year: -55,
    genre: "philosophy",
    category: "roman",
  },
  // ROMAN IMPERIAL PHILOSOPHY
  // {
  //   id: "seneca-letters",
  //   title: "Letters",
  //   author: "Seneca",
  //   year: 65,
  //   genre: "philosophy",
  //   category: "roman",

  //   done: false,
  // },
  {
    title: "Discourses",
    author: "Epictetus",
    year: 108,
    genre: "philosophy",
    category: "roman",
  },
  {
    title: "Meditations",
    author: "Marcus Aurelius",
    year: 170,
    genre: "philosophy",
    category: "roman",
  },
  {
    title: "The Enneads",
    author: "Plotinus",
    year: 270,
    genre: "philosophy",
    category: "roman",
  },

  // --- Christian ---
  // BIBLES
  {
    title: "The Holy Bible",
    author: "Various",
    year: 325,
    genre: "literature",
    category: "christian",
  },
  {
    title: "The Dead Sea Scrolls",
    author: "Various",
    year: 325,
    genre: "literature",
    category: "christian",
  },
  {
    title: "The Nag Hammadi Scriptures",
    author: "Various",
    year: 325,
    genre: "literature",
    category: "christian",
  },
  // EARLY CHRISTIAN HISTORY
  {
    title: "Ecclesiastical History",
    author: "Eusebius",
    year: 325,
    genre: "history",
    category: "christian",
  },
  // {
  //   id: "eusebius-constantine",
  //   title: "The Life of Constantine",
  //   author: "Eusebius",
  //   year: 340,
  //   genre: "history",
  //   category: "christian",

  //   done: false,
  // },
  // {
  //   id: "later-roman-empire",
  //   title: "The Later Roman Empire",
  //   author: "Ammianus Marcellinus",
  //   year: 390,
  //   genre: "history",
  //   category: "christian",

  //   done: false,
  // },
  // AUGUSTINE PHILOSOPHY
  {
    title: "Confessions",
    author: "Saint Augustine",
    year: 400,
    genre: "philosophy",
    category: "christian",
  },
  {
    title: "City of God",
    author: "Saint Augustine",
    year: 426,
    genre: "philosophy",
    category: "christian",
  },
  // POST-AUGUSTIAN HISTORY
  // {
  //   id: "secret-history",
  //   title: "The Secret History",
  //   author: "Procopius",
  //   year: 550,
  //   genre: "history",
  //   category: "christian",

  //   done: false,
  // },
  // --- ISLAM ---
  {
    title: "The Qur'an",
    author: "Muhammad",
    year: 632,
    genre: "literature",
    category: "islamic",
  },
  {
    title: "The Virtuous City",
    author: "Al-Farabi",
    year: 940,
    genre: "philosophy",
    category: "islamic",
  },
  {
    title: "Metaphysics (from The Book of Healing)",
    author: "Avicenna (Ibn Sina)",
    year: 1020,
    genre: "philosophy",
    category: "islamic",
  },
  {
    title: "The Incoherence of the Philosophers",
    author: "Al-Ghazali",
    year: 1095,
    genre: "philosophy",
    category: "islamic",
  },
  {
    title: "The Incoherence of the Incoherence",
    author: "Averroes (Ibn Rushd)",
    year: 1180,
    genre: "philosophy",
    category: "islamic",
  },
  {
    title: "The Guide for the Perplexed",
    author: "Moses Maimonnides",
    year: 1190,
    genre: "philosophy",
    category: "islamic",
  },
  {
    title: "The Muqaddimah",
    author: "Ibn Khaldun",
    year: 1377,
    genre: "history",
    category: "islamic",
  },

  // --- RENAISSANCE ---
  {
    title: "Divine Comedy",
    author: "Dante Alighieri",
    year: 1320,
    genre: "literature",
    category: "renaissance",
  },
  {
    title: "The Canterbury Tales",
    author: "Geoffrey Chaucer",
    year: 1400,
    genre: "literature",
    category: "renaissance",
  },
  {
    title: "The Prince and Discourses on Livy",
    author: "Niccolò Machiavelli",
    year: 1513,
    genre: "philosophy",
    category: "renaissance",
  },
  {
    title: "Ninety-five Theses",
    author: "Martin Luther",
    year: 1517,
    genre: "philosophy",
    category: "renaissance",
  },
  {
    title: "The Freedom of a Christian",
    author: "Martin Luther",
    year: 1520,
    genre: "philosophy",
    category: "renaissance",
  },

  // SCIENTIFIC PHILOSOPHY
  // {
  //   id: "bacon-atlantis",
  //   title: "New Atlantis",
  //   author: "Francis Bacon",
  //   year: 1626,
  //   genre: "literature",
  //   category: "renaissance",

  //   done: false,
  // },
  {
    title: "Meditations on First Philosophy",
    author: "René Descartes",
    year: 1641,
    genre: "philosophy",
    category: "renaissance",
  },
  // {
  //   id: "newton-principia",
  //   title: "The Mathematical Principles of Natural Philosophy",
  //   author: "Isaac Newton",
  //   year: 1687,
  //   genre: "philosophy",
  //   category: "renaissance",

  //   done: false,
  // },
  {
    title:
      "Observations upon the Prophecies of Daniel, and the Apocalypse of St. John",
    author: "Isaac Newton",
    year: 1733,
    genre: "philosophy",
    category: "renaissance",
  },

  // --- ENLIGHTENMENT ---
  {
    title: "Paradise Lost",
    author: "John Milton",
    year: 1667,
    genre: "literature",
    category: "enlightenment",
  },
  // {
  //   id: "milton-regained",
  //   title: "Paradise Regained",
  //   author: "John Milton",
  //   year: 1671,
  //   genre: "literature",
  //   category: "enlightenment",

  //   done: false,
  // },

  // NATURE OF MAN
  {
    title: "Leviathan",
    author: "Thomas Hobbes",
    year: 1651,
    genre: "philosophy",
    category: "enlightenment",
  },
  {
    title: "Essay Concering Human Understanding",
    author: "John Locke",
    year: 1690,
    genre: "philosophy",
    category: "enlightenment",
  },
  {
    title: "A Discourse on the Origin of Inequality",
    author: "Jean-Jacques Rousseau",
    year: 1755,
    genre: "philosophy",
    category: "enlightenment",
  },
  {
    title: "Emile",
    author: "Jean-Jacques Rousseau",
    year: 1762,
    genre: "philosophy",
    category: "enlightenment",
  },
  {
    title: "The Social Contract",
    author: "Jean-Jacques Rousseau",
    year: 1762,
    genre: "philosophy",
    category: "enlightenment",
  },

  // --- Kant ---
  {
    title: "Critique of Pure Reason",
    author: "Immanuel Kant",
    year: 1781,
    genre: "philosophy",
    category: "enlightenment",
  },
  {
    title: "Fundamental Principles to the Metaphysics of Morals",
    author: "Immanuel Kant",
    year: 1785,
    genre: "philosophy",
    category: "enlightenment",
  },
  {
    title: "Critique of Practical Reason",
    author: "Immanuel Kant",
    year: 1788,
    genre: "philosophy",
    category: "enlightenment",
  },

  // --- Hegel ---
  {
    title: "The Philosophy of Right",
    author: "Friedrich Hegel",
    year: 1820,
    genre: "philosophy",
    category: "enlightenment",
  },
  {
    title: "The Philosophy of History",
    author: "Friedrich Hegel",
    year: 1837,
    genre: "philosophy",
    category: "enlightenment",
  },
  // NIETZSCHE
  {
    title: "Thus Spoke Zarathustra",
    author: "Friedrich Nietzsche",
    year: 1883,
    genre: "philosophy",
    category: "enlightenment",
  },

  // --- CAPITALISM ---
  // MARX
  {
    title: "Communist Manifesto",
    author: "Karl Marx",
    year: 1848,
    genre: "philosophy",
    category: "capitalism",
  },
  {
    title: "Capital",
    author: "Karl Marx",
    year: 1867,
    genre: "philosophy",
    category: "capitalism",
  },
  // DARWIN
  {
    title: "On the Origin of Species",
    author: "Charles Darwin",
    year: 1859,
    genre: "philosophy",
    category: "capitalism",
  },
  {
    title: "The Descent of Man",
    author: "Charles Darwin",
    year: 1871,
    genre: "philosophy",
    category: "capitalism",
  },
  // FREUD
  {
    title: "The Interpretation of Dreams",
    author: "Sigmund Freud",
    year: 1900,
    genre: "philosophy",
    category: "capitalism",
  },
  {
    title: "Civilization and its Discontents",
    author: "Sigmund Freud",
    year: 1930,
    genre: "philosophy",
    category: "capitalism",
  },

  // // --- Russia ---
  // {
  //   id: "dostoevsky-crime",
  //   title: "Crime and Punishment",
  //   author: "Fyodor Dostoevsky",
  //   year: 1866,
  //   genre: "literature",
  //   category: "russia",

  //   done: false,
  // },
  {
    title: "On Suicide",
    author: "Emile Durkheim",
    year: 1897,
    genre: "philosophy",
    category: "capitalism",
  },
  {
    title: "The Philosophy of Money",
    author: "Georg Simmel",
    year: 1900,
    genre: "philosophy",
    category: "capitalism",
  },
  {
    title: "The Protestant Work Ethic and the Spirit of Capitalism",
    author: "Max Weber",
    year: 1905,
    genre: "philosophy",
    category: "capitalism",
  },

  // --- Modern day ---
  // {
  //   id: "walcott-omeros",
  //   title: "Omeros",
  //   author: "Derek Walcott",
  //   year: 1990,
  //   genre: "literature",
  //   category: "modern",

  //   done: false,
  // },
  // {
  //   id: "dugin-geopolitics",
  //   title: "The Foundations of Geopolitics: The Geopolitical Future of Russia",
  //   author: "Aleksandr Dugin",
  //   year: 1997,
  //   genre: "philosophy",
  //   category: "modern",

  //   done: false,
  // },
];
